// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "dde0bc09-cf2f-4d7b-a2c1-2d26f38c70fe";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onIOmessageChange();
void onModeChange();
void onThresholdChange();

String iOmessage;
float dhtHumidity;
float dhtTemp;
int mode;
int threshold;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(iOmessage, READWRITE, ON_CHANGE, onIOmessageChange);
  ArduinoCloud.addProperty(dhtHumidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dhtTemp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mode, READWRITE, ON_CHANGE, onModeChange);
  ArduinoCloud.addProperty(threshold, READWRITE, ON_CHANGE, onThresholdChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
